include:
  - template: Terraform/Base.gitlab-ci.yml

variables:
  IMAGE_NAME: tmh9x/gitlab_example-eks
  IMAGE_TAG: $CI_COMMIT_TAG
  AWS_ACCESS_KEY_ID:

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./backend
    - docker push $IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: "$CI_COMMIT_TAG"

deployment:
  stage: deploy
  script:
    - ssh -i $SSH_KEY_PEM ec2-user@ec2-18-199-121-239.eu-central-1.compute.amazonaws.com && sudo docker run -d -p 80:3000 $IMAGE_NAME:$IMAGE_TAG
    - aws s3 cp ./frontend/src/index.html s3://example-eks-s3 --acl public-read
